version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - application

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - application

  php-fpm:
    build:
      context: php-fpm
      dockerfile: Dockerfile
      args:
        - XDEBUG_PORT=${XDEBUG_PORT}
    container_name: php-fpm
    volumes:
      - ../:/var/www/html
    # https://stackoverflow.com/questions/68872388/laravel-and-docker-permission-issue-cant-save-files
    user: "1000:1000"
    networks:
      - application
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  application:
